Project setup
SirriRyisa/HTML-Project pull request #1
Opened 2021-11-23 14:29 UTC by SirriRyisa

Add index.html
Add style.css
Add linters check

2021-11-23 15:14 UTC, alonsofl requested changes
Hi @SirriRyisa,

You have done a great job so far! :muscle:
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## To highlight :dart:
- Linters working properly :heavy_check_mark:
- Well documented PR :heavy_check_mark:
- Your design looks great! :fire:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-23 15:14 UTC, alonsofl commented on index.html
> +<!DOCTYPE html>
- [ ] You have done an excellent job with your project and it's looking great :fire: but one of the requirements it's to add a descriptive README and it's recommended to use [this README template](https://github.com/microverseinc/readme-template) and customize it for your project :wink:
![image](https://user-images.githubusercontent.com/81522435/143049865-f0ff32af-c874-4e4a-a630-3610dd84c9b2.png)

2021-11-23 16:51 UTC, alonsofl approved these changes
Hi @SirriRyisa,

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-23 16:55 UTC, SirriRyisa commented
Yeeeee!!!! 🥳🥳🥳 Thank you alonsofl. I will merge the project now.

On Tue, 23 Nov 2021 at 17:51 Alonso Falconi ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @SirriRyisa <https://github.com/SirriRyisa>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
>
>
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/SirriRyisa/HTML-Project/pull/1#pullrequestreview-813938677>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU2VUOSJXPCMHEIJPTACRHDUNPBANANCNFSM5ITUYDAQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-23 16:55 UTC, merged

2021-11-29 09:28 UTC, Rustamxon7 reviewed
Hi @SirriRyisa,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Your code is not ready for review. Please make sure that you have a fresh Pull Request that will show the changes required in a specific project. 
You can either create a brand new repository or just reverting previous changes and opening a new PR. 
We need to see piece of code so that we can perform fresh review once again on the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---

_Invalid Code Review Request **does not count** into the code reviews limit._